#!/bin/bash

usage="usage: ipod_to_folder <from-folder> <destination-folder>"

if [ $# -lt 2 ]; then
	echo $usage
	exit 1
fi

# &> means to redirect both stdout and stderr to /dev/null
# the exit code for the hash command is stored in $?
hash id3info &> /dev/null
if [ $? -eq 1 ]; then
    echo >&2 "id3info not found. Install and run the script again"
    echo "sudo apt-get install libid3-tools"
    exit 1
fi


for x in `find $1 -name *.mp3`
do
art=`id3info $x | grep "performer" | cut -d ":" -f 2-`
name=`id3info $x | grep "Title" | cut -d ":" -f 2-`
album=`id3info $x | grep "Album" | cut -d ":" -f 2-`
name=`echo $name | tr " " "_"`
art=`echo $art | tr " " "_"`
album=`echo $album | tr " " "_"`
echo $album ":" $art ":" $name

if [ ! -d $2"/"$art"/"$album ]; then
    mkdir -p $2"/"$art"/"$album
fi
cp $x $2"/"$art"/"$album"/"$name

done
